name: ElytraDisabled
version: '1.1.0'
main: ua.krint.elytraDisabled.ElytraDisabled
author: Krint
api-version: '1.18'

commands:
  elytra-disabled:
    description: Main plugin command
    usage: /<command> [reload]
    aliases: [ed, elytradisabled]

permissions:
  elytradisabled.reload:
    description: Allows to reload plugin configuration
    default: op
  elytradisabled.bypass:
    description: Allows to use elytra in disabled worlds
    default: op
  elytradisabled.update.notify:
    description: Receive notifications about plugin updates
    default: op